AWSTemplateFormatVersion: '2010-09-09'
Description: Test bucket using Cloud Formation

Parameters:
  BucketName:
    Type: String
    Default: cf-bucket-rp-r
Resources:

  MainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      VersioningConfiguration:
        Status: Suspended

      ## Block public access
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  MainBucketName:
    Description: Name of the main bucket
    Value: !Ref MainBucket
